services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9999:5173"
    networks:
      - tradehub-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:5050
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:5050"
    networks:
      - tradehub-network
    volumes:
      - ./backend:/app
    command: python server.py

networks:
  tradehub-network:
    driver: bridge
